#!/usr/bin/env bash
# This script will check if a host is on the network.

# Check if an argument is provided
if [ "$1" ]
then
    # Ping the provided IP address five times
    ping -c 5 "$1"
else
    # Display the usage message if no IP address is provided
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
