#!/usr/bin/env bash
# Check if an IP address was passed as an argument
if [ $# -eq 0 ]; then
     echo "You must provide an IP address as an argument."
     exit 1
fi

# Get the IP address of the argument
ip_address=$1

# Ping the IP address
ping -c 4 $ip_address
